# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2

updates:
  - package-ecosystem: nuget
    directories:
      - /NTComponents.Charts
      - /Tests/AotCompatibility.TestApp
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: America/Denver
    groups:
      nuget-minor-and-patch:
        patterns: ['*']
        update-types: [minor, patch]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: '06:00'
      timezone: America/Denver
    groups:
      actions-minor-and-patch:
        patterns: ['*']
        update-types: [minor, patch]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly
      day: thursday
      time: '06:00'
      timezone: America/Denver
    commit-message:
      prefix: chore
      include: scope
