using SkiaSharp;
using System.Collections.Generic;
using NTComponents.Charts.Core.Series;

namespace NTComponents.Charts.Core;

public class TooltipInfo
{
    public string? Header { get; set; }
    public List<TooltipLine> Lines { get; set; } = [];
}

public struct TooltipLine
{
    public string Label { get; set; }
    public string Value { get; set; }
    public SKColor Color { get; set; }
}

/// <summary>
///     Provides series and hover context for building custom tooltip content.
/// </summary>
/// <typeparam name="TData">The chart data type.</typeparam>
public sealed class NTSeriesTooltipContext<TData> where TData : class {
    /// <summary>
    ///     Gets the series that owns the tooltip.
    /// </summary>
    public required NTBaseSeries<TData> Series { get; init; }

    /// <summary>
    ///     Gets the hovered data item.
    /// </summary>
    public required TData Data { get; init; }

    /// <summary>
    ///     Gets the hovered point index when available.
    /// </summary>
    public int? PointIndex { get; init; }

    /// <summary>
    ///     Gets the default tooltip payload generated by the chart.
    /// </summary>
    public required TooltipInfo DefaultInfo { get; init; }

    /// <summary>
    ///     Gets the hovered bar segment label when the tooltip originated from a segmented bar.
    /// </summary>
    public string? SegmentLabel { get; init; }

    /// <summary>
    ///     Gets the hovered bar segment value when the tooltip originated from a segmented bar.
    /// </summary>
    public decimal? SegmentValue { get; init; }

    /// <summary>
    ///     Gets the hovered bar segment color when the tooltip originated from a segmented bar.
    /// </summary>
    public SKColor? SegmentColor { get; init; }
}
