using SkiaSharp;
using System.Collections.Generic;
using NTComponents.Charts.Core.Series;

namespace NTComponents.Charts.Core;

/// <summary>
///     Contains the data used to populate a chart tooltip.
/// </summary>
public class TooltipInfo
{
    /// <summary>Gets or sets the optional header text shown at the top of the tooltip.</summary>
    public string? Header { get; set; }

    /// <summary>Gets or sets the collection of label/value lines displayed in the tooltip body.</summary>
    public List<TooltipLine> Lines { get; set; } = [];
}

/// <summary>
///     Represents a single label/value row inside a chart tooltip.
/// </summary>
public struct TooltipLine
{
    /// <summary>Gets or sets the descriptive label for this line.</summary>
    public string Label { get; set; }

    /// <summary>Gets or sets the formatted value string for this line.</summary>
    public string Value { get; set; }

    /// <summary>Gets or sets the color swatch associated with this line.</summary>
    public SKColor Color { get; set; }
}

/// <summary>
///     Provides series and hover context for building custom tooltip content.
/// </summary>
/// <typeparam name="TData">The chart data type.</typeparam>
public sealed class NTSeriesTooltipContext<TData> where TData : class {
    /// <summary>
    ///     Gets the series that owns the tooltip.
    /// </summary>
    public required NTBaseSeries<TData> Series { get; init; }

    /// <summary>
    ///     Gets the hovered data item.
    /// </summary>
    public required TData Data { get; init; }

    /// <summary>
    ///     Gets the hovered point index when available.
    /// </summary>
    public int? PointIndex { get; init; }

    /// <summary>
    ///     Gets the default tooltip payload generated by the chart.
    /// </summary>
    public required TooltipInfo DefaultInfo { get; init; }

    /// <summary>
    ///     Gets the hovered bar segment label when the tooltip originated from a segmented bar.
    /// </summary>
    public string? SegmentLabel { get; init; }

    /// <summary>
    ///     Gets the hovered bar segment value when the tooltip originated from a segmented bar.
    /// </summary>
    public decimal? SegmentValue { get; init; }

    /// <summary>
    ///     Gets the hovered bar segment color when the tooltip originated from a segmented bar.
    /// </summary>
    public SKColor? SegmentColor { get; init; }
}
